import type { IconType } from "react-icons";
import {
	SiAndroid,
	SiBun,
	SiC,
	SiDart,
	SiEspressif,
	SiExpress,
	SiFlutter,
	SiFramer,
	SiJavascript,
	SiJsonwebtokens,
	SiJupyter,
	SiMongodb,
	SiNodedotjs,
	SiNumpy,
	SiOpencv,
	SiOpenjdk,
	SiPostgresql,
	SiPuppeteer,
	SiPython,
	SiReact,
	SiRust,
	SiTailwindcss,
	SiTauri,
	SiTensorflow,
	SiTypescript,
} from "react-icons/si";

const TECH_ICONS: Record<string, IconType> = {
	react: SiReact,
	rust: SiRust,
	tauri: SiTauri,
	mongodb: SiMongodb,
	python: SiPython,
	opencv: SiOpencv,
	"esp32-cam": SiEspressif,
	"embedded c": SiC,
	flutter: SiFlutter,
	"tensorflow lite": SiTensorflow,
	dart: SiDart,
	numpy: SiNumpy,
	jupyter: SiJupyter,
	typescript: SiTypescript,
	"node.js": SiNodedotjs,
	"express.js": SiExpress,
	postgresql: SiPostgresql,
	tailwindcss: SiTailwindcss,
	"tailwind css": SiTailwindcss,
	bun: SiBun,
	jwt: SiJsonwebtokens,
	javascript: SiJavascript,
	"framer motion": SiFramer,
	puppeteer: SiPuppeteer,
	java: SiOpenjdk,
	android: SiAndroid,
};

export const getTechIcon = (name: string): IconType | null =>
	TECH_ICONS[name.trim().toLowerCase()] ?? null;
